base:
  project: Thyroid_disorder_prediction
  random_state: 42
  target_col: class

data_source:
  source: data_given/hypothyroid.csv

split_data:
  train_path: datas/raw/train_raw.csv
  test_path: datas/raw/test_raw.csv
  text_size: 0.3

preprocessed:
  train_path: datas/processed/train_processed_raw.csv
  test_path: datas/processed/test_processed_raw.csv


